my_service:
    path: /technology
    methods: [POST]
    controller: app.tech_controller:newTech

my_location:
    path: /technology/{id}
    methods: [GET]
    controller: app.tech_controller:getTechnology

