# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:

    app.db_repository:
        class: 'App\Repository\TechnologyRepository'
        arguments:
            - '@doctrine.dbal.delia_connection'

    app.tech_validator:
        class: 'App\Validator\TagValidator'
        arguments:
            - '@app.db_repository'

    app.tech_service:
        class: 'App\Service\TechnologyService'
        arguments: ['@app.db_repository','@Symfony\Component\Validator\Validator\ValidatorInterface','@app.tech_validator']

    app.tech_controller:
        class: 'App\Controller\TechnologyController'
        public: true
        arguments:
            - '@app.tech_service'


