App\Entity\Technology:
  properties:
    name:
      - NotBlank: { message: Name cannot be blank }
    picture:
      - NotNull: { message: Picture cannot be null }
      - Image:
         notFoundMessage: Image not uploaded
         uploadErrorMessage: The image could not upload. Try again
         mimeTypes: [image/jpeg, image/jpg]
         mimeTypesMessage: The file types must be jpg or jpeg


